import type { SupportedLang } from "./languages";

/**
 * Fixed opening line each role-play persona speaks first, per scenario and
 * target language. Saved (not LLM-generated) so the line appears on screen
 * instantly and the audio can be synthesized on the fly. Keep each to one short,
 * natural conversational sentence in character.
 *
 * To add a scenario or language, extend this map. EN/FR are hand-checked
 * (the visible UI languages); the rest are conversational translations.
 */
export const ROLE_PLAY_OPENINGS: Record<
  string,
  Record<SupportedLang, string>
> = {
  coffee: {
    en: "Morning! What can I get started for you?",
    fr: "Bonjour ! Qu'est-ce que je vous sers ?",
    de: "Guten Morgen! Was darf ich Ihnen bringen?",
    it: "Buongiorno! Cosa le preparo?",
    es: "¡Buenos días! ¿Qué le pongo?",
    pt: "Bom dia! O que vai ser?",
    tr: "Günaydın! Ne alırsınız?",
    sv: "God morgon! Vad får det lov att vara?",
    da: "Godmorgen! Hvad kan jeg friste med?",
    ru: "Доброе утро! Что вам приготовить?",
    ro: "Bună dimineața! Ce vă pregătesc?",
    hu: "Jó reggelt! Mit hozhatok?",
    ja: "おはようございます！ご注文は何にしましょうか？",
    zh: "早上好！您想点点什么？",
    ko: "좋은 아침이에요! 뭐 드릴까요?",
  },
  directions: {
    en: "Oh, hi — can I help you find somewhere?",
    fr: "Ah, bonjour — je peux vous aider à trouver votre chemin ?",
    de: "Oh, hallo — kann ich Ihnen helfen, etwas zu finden?",
    it: "Oh, salve — la posso aiutare a trovare qualcosa?",
    es: "Ah, hola — ¿le ayudo a encontrar algún sitio?",
    pt: "Olá — posso ajudar a encontrar algum lugar?",
    tr: "Merhaba — bir yer mi arıyorsunuz, yardımcı olayım mı?",
    sv: "Åh, hej — kan jag hjälpa dig att hitta något?",
    da: "Åh, hej — kan jeg hjælpe dig med at finde vej?",
    ru: "О, здравствуйте — помочь вам что-то найти?",
    ro: "O, bună — vă pot ajuta să găsiți un loc?",
    hu: "Ó, üdv — segíthetek megtalálni valamit?",
    ja: "あ、こんにちは。どこかお探しですか？",
    zh: "哦，你好——需要我帮你指路吗？",
    ko: "아, 안녕하세요 — 어디 찾으시는 거 도와드릴까요?",
  },
  party: {
    en: "Hi there, I'm Sofia! So how do you know our host?",
    fr: "Salut, moi c'est Sofia ! Alors, tu connais l'hôte comment ?",
    de: "Hi, ich bin Sofia! Und woher kennst du den Gastgeber?",
    it: "Ciao, sono Sofia! Allora, come conosci il padrone di casa?",
    es: "¡Hola, soy Sofía! ¿De qué conoces al anfitrión?",
    pt: "Oi, eu sou a Sofia! Então, como conhece o anfitrião?",
    tr: "Selam, ben Sofia! Ev sahibini nereden tanıyorsun?",
    sv: "Hej, jag heter Sofia! Hur känner du värden?",
    da: "Hej, jeg hedder Sofia! Hvordan kender du værten?",
    ru: "Привет, я Софи! А ты откуда знаешь хозяина вечеринки?",
    ro: "Bună, eu sunt Sofia! Tu de unde îl cunoști pe gazdă?",
    hu: "Szia, Sofia vagyok! Te honnan ismered a házigazdát?",
    ja: "こんにちは、ソフィアです！ホストとはどういう知り合いですか？",
    zh: "嗨，我是索菲娅！你是怎么认识主人的？",
    ko: "안녕하세요, 저는 소피아예요! 호스트랑은 어떻게 아는 사이예요?",
  },
  hotel: {
    en: "Good evening, welcome! Do you have a reservation with us?",
    fr: "Bonsoir et bienvenue ! Vous avez une réservation chez nous ?",
    de: "Guten Abend, herzlich willkommen! Haben Sie bei uns reserviert?",
    it: "Buonasera, benvenuto! Ha una prenotazione da noi?",
    es: "¡Buenas noches, bienvenido! ¿Tiene una reserva con nosotros?",
    pt: "Boa noite, bem-vindo! Tem reserva connosco?",
    tr: "İyi akşamlar, hoş geldiniz! Rezervasyonunuz var mıydı?",
    sv: "God kväll och välkommen! Har ni en bokning hos oss?",
    da: "Godaften og velkommen! Har du en reservation hos os?",
    ru: "Добрый вечер, добро пожаловать! У вас забронирован номер?",
    ro: "Bună seara, bun venit! Aveți o rezervare la noi?",
    hu: "Jó estét, üdvözlöm! Van nálunk foglalása?",
    ja: "こんばんは、ようこそ。ご予約はございますか？",
    zh: "晚上好，欢迎光临！请问您有预订吗？",
    ko: "안녕하세요, 어서 오세요! 예약하셨나요?",
  },
  doctor: {
    en: "Hello, come on in. So, what's brought you in today?",
    fr: "Bonjour, entrez donc. Alors, qu'est-ce qui vous amène aujourd'hui ?",
    de: "Hallo, kommen Sie herein. Was führt Sie denn heute zu mir?",
    it: "Salve, prego si accomodi. Allora, cosa la porta qui oggi?",
    es: "Hola, pase. ¿Qué le trae por aquí hoy?",
    pt: "Olá, faça favor de entrar. O que o traz cá hoje?",
    tr: "Merhaba, buyurun girin. Bugün sizi buraya getiren nedir?",
    sv: "Hej, kom in. Vad är det som för dig hit idag?",
    da: "Hej, kom indenfor. Hvad bringer dig herind i dag?",
    ru: "Здравствуйте, проходите. Что вас сегодня беспокоит?",
    ro: "Bună ziua, poftiți. Ce vă aduce la mine astăzi?",
    hu: "Jó napot, fáradjon be. Mi járatban van ma nálam?",
    ja: "こんにちは、どうぞお入りください。今日はどうされましたか？",
    zh: "您好，请进。今天哪里不舒服？",
    ko: "안녕하세요, 들어오세요. 오늘은 어디가 불편해서 오셨어요?",
  },
  interview: {
    en: "Thanks for coming in. To start, tell me a bit about yourself.",
    fr: "Merci d'être venu. Pour commencer, parlez-moi un peu de vous.",
    de: "Danke, dass Sie da sind. Erzählen Sie mir zum Einstieg ein bisschen über sich.",
    it: "Grazie per essere venuto. Per iniziare, mi parli un po' di lei.",
    es: "Gracias por venir. Para empezar, cuénteme un poco sobre usted.",
    pt: "Obrigado por ter vindo. Para começar, fale-me um pouco sobre si.",
    tr: "Geldiğiniz için teşekkürler. Başlangıç olarak, biraz kendinizden bahseder misiniz?",
    sv: "Tack för att du kom. Till att börja med, berätta lite om dig själv.",
    da: "Tak fordi du kom. Til at starte med, fortæl lidt om dig selv.",
    ru: "Спасибо, что пришли. Для начала расскажите немного о себе.",
    ro: "Mulțumesc că ați venit. Ca să începem, spuneți-mi câte ceva despre dumneavoastră.",
    hu: "Köszönöm, hogy eljött. Kezdésként meséljen egy kicsit magáról.",
    ja: "本日はお越しいただきありがとうございます。まず、少し自己紹介をお願いできますか？",
    zh: "感谢您今天过来。首先，请简单介绍一下您自己。",
    ko: "와 주셔서 감사합니다. 우선, 본인 소개를 간단히 해 주시겠어요?",
  },
  complaint: {
    en: "Thanks for calling support — how can I help today?",
    fr: "Merci d'appeler le service client — que puis-je faire pour vous ?",
    de: "Danke für Ihren Anruf beim Support — wie kann ich Ihnen helfen?",
    it: "Grazie per aver chiamato l'assistenza — come posso aiutarla oggi?",
    es: "Gracias por llamar a soporte — ¿en qué puedo ayudarle hoy?",
    pt: "Obrigado por ligar para o apoio — em que posso ajudar hoje?",
    tr: "Destek hattını aradığınız için teşekkürler — bugün nasıl yardımcı olabilirim?",
    sv: "Tack för att du ringer supporten — hur kan jag hjälpa dig idag?",
    da: "Tak fordi du ringer til support — hvordan kan jeg hjælpe i dag?",
    ru: "Спасибо, что обратились в поддержку — чем могу помочь?",
    ro: "Mulțumim că ați sunat la suport — cu ce vă pot ajuta astăzi?",
    hu: "Köszönjük, hogy az ügyfélszolgálatot hívta — miben segíthetek ma?",
    ja: "サポートにお電話ありがとうございます。本日はどのようなご用件でしょうか？",
    zh: "感谢您致电客服——今天有什么可以帮您的？",
    ko: "고객 지원에 전화 주셔서 감사합니다 — 오늘 무엇을 도와드릴까요?",
  },
  "phone-friend": {
    en: "Hey! It's been ages — how are you?",
    fr: "Hé ! Ça fait une éternité — comment tu vas ?",
    de: "Hey! Ewig nicht gehört — wie geht's dir?",
    it: "Ehi! Quanto tempo — come stai?",
    es: "¡Ey! Cuánto tiempo — ¿cómo estás?",
    pt: "Ei! Há quanto tempo — como estás?",
    tr: "Hey! Çok uzun zaman oldu — nasılsın?",
    sv: "Hej! Det var längesen — hur mår du?",
    da: "Hej! Det er længe siden — hvordan har du det?",
    ru: "Привет! Сто лет не виделись — как ты?",
    ro: "Hei! A trecut o veșnicie — ce mai faci?",
    hu: "Szia! Ezer éve nem hallottunk egymásról — hogy vagy?",
    ja: "もしもし！久しぶり〜元気にしてた？",
    zh: "嘿！好久不见——你最近怎么样？",
    ko: "야! 진짜 오랜만이다 — 잘 지냈어?",
  },
  meeting: {
    en: "Welcome to the team! Why don't you introduce yourself to everyone?",
    fr: "Bienvenue dans l'équipe ! Tu veux bien te présenter à tout le monde ?",
    de: "Willkommen im Team! Möchtest du dich kurz allen vorstellen?",
    it: "Benvenuto nel team! Ti va di presentarti a tutti?",
    es: "¡Bienvenido al equipo! ¿Por qué no te presentas a todos?",
    pt: "Bem-vindo à equipa! Queres apresentar-te a todos?",
    tr: "Ekibe hoş geldin! Kendini herkese tanıtmak ister misin?",
    sv: "Välkommen till teamet! Vill du presentera dig för alla?",
    da: "Velkommen til teamet! Vil du præsentere dig for alle?",
    ru: "Добро пожаловать в команду! Представишься всем?",
    ro: "Bun venit în echipă! Vrei să te prezinți tuturor?",
    hu: "Üdv a csapatban! Bemutatkoznál mindenkinek?",
    ja: "チームへようこそ！みんなに自己紹介してもらえますか？",
    zh: "欢迎加入团队！要不要跟大家做个自我介绍？",
    ko: "팀에 오신 걸 환영해요! 모두에게 자기소개 좀 해 주실래요?",
  },
  emergency: {
    en: "Good evening. Try to stay calm — how can I help you?",
    fr: "Bonsoir. Essayez de rester calme — comment puis-je vous aider ?",
    de: "Guten Abend. Bleiben Sie ruhig — wie kann ich Ihnen helfen?",
    it: "Buonasera. Cerchi di stare calmo — come posso aiutarla?",
    es: "Buenas noches. Intente mantener la calma — ¿en qué puedo ayudarle?",
    pt: "Boa noite. Tente manter a calma — como posso ajudá-lo?",
    tr: "İyi akşamlar. Sakin olmaya çalışın — size nasıl yardımcı olabilirim?",
    sv: "God kväll. Försök att hålla dig lugn — hur kan jag hjälpa dig?",
    da: "Godaften. Prøv at holde dig rolig — hvordan kan jeg hjælpe dig?",
    ru: "Добрый вечер. Постарайтесь успокоиться — чем я могу помочь?",
    ro: "Bună seara. Încercați să rămâneți calm — cum vă pot ajuta?",
    hu: "Jó estét. Próbáljon nyugodt maradni — miben segíthetek?",
    ja: "こんばんは。落ち着いてくださいね。どうされましたか？",
    zh: "晚上好。请尽量保持冷静——有什么可以帮您的？",
    ko: "안녕하세요. 진정하시고요 — 무엇을 도와드릴까요?",
  },
};

/**
 * The saved opening line for a scenario in a target language, or null if none
 * is defined (caller should fall back to live generation). Falls back to the
 * English line if the scenario exists but the language is missing.
 */
export function getOpeningLine(
  scenarioId: string,
  lang: string,
): string | null {
  const byLang = ROLE_PLAY_OPENINGS[scenarioId];
  if (!byLang) return null;
  return byLang[lang as SupportedLang] ?? byLang.en ?? null;
}
